### ISSUE TITLE
social media feed on intranet is outdated for blog posts

### ISSUE THREAD

**Issue by deniseOme** [opentargets/opentargets.github.io#109]
Not sure what happen to the last 6 blog posts that somehow don't appear on the social media feed on home.opentargets.org. The latest blog to appear is:

http://blog.opentargets.org/2019/02/20/open-targets-platform-release-19-02-is-out/

As it stands we are missing a few important ones such as latest Genetics and Platform releases and Glenn's update on adding a data source.

The full list of missing posts is below:

- http://blog.opentargets.org/2019/03/19/from-antibody-to-zinc-finger-an-a-z-of-open-targets-5/

- http://blog.opentargets.org/2019/03/29/updated-adding-a-data-source-to-the-open-targets-pipeline/

- http://blog.opentargets.org/2019/04/05/avoiding-confusion-in-disease-biology-with-ontologies/

- http://blog.opentargets.org/2019/04/09/open-targets-genetics-release-is-out/

- http://blog.opentargets.org/2019/05/01/open-targets-platform-release-19-04-is-out/

- http://blog.opentargets.org/2019/05/28/using-crispr-priority-score-to-identify-targets-in-cancer-drug-discovery/

@andrewhercules, would you be able to have a look at this please?

![Screen Shot 2019-06-06 at 16 14 13](https://user-images.githubusercontent.com/6472381/59044551-3c423080-8876-11e9-896c-3fe20f22525b.png)

**Comment by andrewhercules** [comment]
I have raised this with the web dev team and will update this ticket once I have a response

**Comment by andrewhercules** [comment]
Issue has been resolved - 5 most recent blog posts are now showing

![Screenshot 2019-06-12 at 11 37 21](https://user-images.githubusercontent.com/7490258/59344719-8b6ce300-8d06-11e9-983d-50d95af07c28.png)
