### ISSUE TITLE
typo in the description of Open Targets Genetics in the resources page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/opentargets.github.io#136]
We have it as `assoication`; it should be `association` in the [resources](https://www.opentargets.org/resources/) section for Open Targets Genetics

<img width="399" alt="Screen Shot 2019-10-21 at 10 30 30" src="https://user-images.githubusercontent.com/6472381/67193900-0305f980-f3ee-11e9-87df-321cc3685ef6.png">

**Comment by andrewhercules** [comment]
Issue closed as typo has been fixed
