### ISSUE TITLE
pages don't appear in netlify deploy

### ISSUE THREAD

**Issue by elipapa** [opentargets/opentargets.github.io#19]
we have noticed one deploy in which a page was not rendered. 

A redeploy of the same code fixed the issue. 

a tool like [html proofer](https://github.com/gjtorikian/html-proofer) may help, but it will need to be set up on a CI system. 
For eg:
https://jekyllrb.com/docs/continuous-integration/circleci/

**Comment by elipapa** [comment]
@LucaFumis @HollyFoster if this were to happen again we can consider doing something.

**Comment by andrewhercules** [comment]
Closing this issue as Netlify has made slight amendments to deploys and branch previews
