### ISSUE TITLE
Update homepage with details of CRISPR project and link to press release

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/opentargets.github.io#91]
Add the following text to the homepage:

"Open Targets is pleased to announce that one our first experimental projects has published its findings in Nature [link to paper]. In one of the largest studies of its kind, researchers used CRISPR technology to disrupt every gene in over 300 cancer models from 30 cancer types. They discovered thousands of key genes essential for cancer’s survival and developed a new system to prioritise and rank 600 drug targets that show the most promise for development into treatments. Read the press release [link to press release @ Sanger]."

**Comment by deniseOme** [comment]
Link to the Sanger press release: https://www.sanger.ac.uk/news/view/new-cancer-drug-targets-accelerate-path-precision-medicine

#555

**Comment by deniseOme** [comment]
Minor typo in bold below:

Open Targets is pleased to announce that one **of** our first experimental projects has published its findings in Nature (Behan et. al, 2019). In one of the largest studies of its kind, researchers used CRISPR-Cas9 technology to conduct whole-genome drop out screens in over 300 cancer models from 30 different cancer types. They discovered thousands of key genes essential for cancer’s survival and developed a new system to prioritise and rank 600 drug targets that show the most promise for development into treatments.

**Comment by andrewhercules** [comment]
Good spot. Thanks! I've fixed the typo. :)

**Comment by andrewhercules** [comment]
Issue closed as homepage is updated
